name: 'Setup Ubuntu18.04'
description: 'Install all the needed standard packages using apt and pip.'

runs:
  using: "composite"
  steps:
    #
    # build and install all dependencies.
    #

    # apt dependencies.
    - name: "apt install"
      shell: bash 
      run: |
        sudo apt update
        sudo apt install -y build-essential
        sudo apt install -y python3-pip
        sudo apt install -y cmake
        sudo apt install -y libcereal-dev
        sudo apt install -y libyaml-cpp-dev
        sudo apt install -y libboost-all-dev
        sudo apt install -y libgtest-dev
        sudo apt install -y libeigen3-dev
        sudo apt install -y libedit-dev
        sudo apt install -y doxygen
        sudo apt install -y libncurses5-dev
        sudo apt install -y freeglut3-dev
        sudo apt install -y libxmu-dev
        sudo apt install -y git
        sudo apt install -y ssh
        sudo apt install -y lsb-release
      

    # pip dependencies.
    - name: "pip install"
      shell: bash
      run: |
        sudo -H pip3 install -U pip
        sudo -H pip3 install -U "setuptools>=40.0"
        sudo -H pip3 install -U colcon-common-extensions
        sudo -H pip3 install -U treep
        sudo -H pip3 install -U fyplot
        sudo -H pip3 install -U pyside2
        sudo -H pip3 install -U empy
        sudo -H pip3 install -U flake8
        sudo -H pip3 install -U m2r
        sudo -H pip3 install -U sphinx
        sudo -H pip3 install -U pyjson
        sudo -H pip3 install -U recommonmark
        sudo -H pip3 install -U sphinx_rtd_theme
        sudo -H pip3 install -U sphinxcontrib-moderncmakedomain
        sudo -H pip3 install -U breathe
        sudo -H pip3 install -U pytest
        sudo -H pip3 install -U gco

    # Set python3.6 by default
    - name: Set python3 by default
      shell: bash
      run: >
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1

    # Setup git account:
    - name: Set git account
      shell: bash
      run: |
        git config --global user.email "mnaveau@tue.mpg.de"
        git config --global user.name "MPI-IS-BambooAgent"
