name: 'Setup Ubuntu18.04'
description: 'Install all the needed standard packages using apt and pip.'
runs:
  using: "composite"
  steps:
    #
    # Activate the secret ssh key
    #
    - uses: webfactory/ssh-agent@v0.5.2
      with:
        ssh-private-key: ${{ secrets.GA_SSH_PRIVATE_KEY }}

    #
    # build and install all dependencies.
    #
    - name: Install apt dependencies.
      run: >
        sudo apt update && sudo apt install -y
        build-essential python3-pip cmake libcereal-dev	libyaml-cpp-dev
        libboost-all-dev libgtest-dev libeigen3-dev libedit-dev doxygen
        libncurses5-dev freeglut3-dev libxmu-dev git ssh lsb-release

    - name: Install pip dependencies.
      run: >
        sudo -H pip3 install "setuptools>=40.0" && sudo -H pip3 install
        colcon-common-extensions treep fyplot pyside2 empy flake8 m2r sphinx
        pyjson recommonmark sphinx_rtd_theme sphinxcontrib-moderncmakedomain
        breathe pytest
