name: 'Clone and build'
description: '"git clone" and "treep --clone" downloading sources.'

inputs:
  treep_configurations:
    description: 'Treep configurations to clone'
    required: false
    default: ''
  projects_or_repos:
    description: 'Semi colon (:) separated list of repositories to clone.'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    #
    # Create the build folders
    #
    - name: Create separate environment for build and source dependencies.
      shell: bash
      run: >
        mkdir -p ${BUILD_FOLDER} &&
        mkdir -p ${DEVEL_FOLDER}/workspace/src

    #
    # Clone all.
    #
    - name: Clone the treep configurations.
      shell: bash
      working-directory: ${{github.workspace}}/devel/
      run: >
        IFS=':' read -ra configurations <<< "$INPUT_TREEP_CONFIGURATIONS" &&
        for configuration in "${configurations[@]}"; do
          echo git clone $configuration &&
          git clone $configuration ;
        done

    - name: Treep clone the repositories or projects.
      shell: bash
      working-directory: ${{github.workspace}}/devel/
      run: >
        IFS=':' read -ra projects_or_repos <<< "$INPUT_PROJECTS_OR_REPOS" &&
        for project_or_repo in "${projects_or_repos[@]}"; do
          echo treep --clone $project_or_repo &&
          treep --clone $project_or_repo ;
        done

    #
    # Build the source dependencies
    #
    - name: Build the dependencies.
      working-directory: ${{github.workspace}}/devel/workspace
      shell: bash
      run: >
        colcon build --cmake-args
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DPYBIND11_TEST=OFF
        -DBUILD_TESTING=OFF
    