name: 'CMake, Build, and CTest'
description: 'Apply CMake on the checkout repository, build it and apply CTest.'

inputs:
  cmake_args:
    description: 'Arguments to give to CMake.'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        echo cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE ${{ inputs.cmake_args }}
        source ${{github.workspace}}/devel/workspace/install/setup.bash
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        echo cmake --build . --config $BUILD_TYPE ${{ inputs.cmake_args }}
        source ${{github.workspace}}/devel/workspace/install/setup.bash
        cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        echo env CTEST_OUTPUT_ON_FAILURE=1 ctest -C $BUILD_TYPE ${{ inputs.cmake_args }}
        source ${{github.workspace}}/devel/workspace/install/setup.bash &&
        env CTEST_OUTPUT_ON_FAILURE=1 ctest -C $BUILD_TYPE




    